services:
  user_server:
    build:
      context: ./backend
      dockerfile: services/user/Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - backend/services/user/.env
    depends_on:
      - user_db
    networks:
      - backend-network

  auth_server:
    build:
      context: ./backend
      dockerfile: services/auth/Dockerfile
    ports:
      - "50052:50052"
    env_file:
      - backend/services/auth/.env
    depends_on:
      - user_db
    networks:
      - backend-network

  tenant_server:
    build:
      context: ./backend
      dockerfile: services/tenant/Dockerfile
    ports:
      - "50053:50053"
    env_file:
      - backend/services/tenant/.env
    depends_on:
      - tenant_db
    networks:
      - backend-network

  user_db:
    image: postgres:13
    restart: always
    env_file:
      - backend/services/user/.env
    ports:
      - "5432:5432"
    networks:
      - backend-network
    volumes:
      - user-db-data:/var/lib/postgresql/data

  tenant_db:
    image: postgres:13
    restart: always
    env_file:
      - backend/services/tenant/.env
    ports:
      - "5433:5432"
    networks:
      - backend-network
    volumes:
      - tenant-db-data:/var/lib/postgresql/data

volumes:
  user-db-data:
    driver: local
  tenant-db-data:
    driver: local

networks:
  backend-network:
    driver: bridge
