syntax = "proto3";

package user;

option go_package = "github.com/dijonron/recipe-box/proto/user";

service User {
  // Create a new user.
  rpc CreateUser (CreateUserRequest) returns (CreateUserResponse);
  // Get user details by user ID.
  rpc GetUser (GetUserRequest) returns (GetUserResponse);
}

message GetUserRequest {
  string user_id = 1;
}

message GetUserResponse {
  UserDetails user = 1;
  bool success = 2;
  string error_message = 3;
}

message CreateUserRequest {
  string username = 1;
  string email = 2;
  string password = 3;
}

message CreateUserResponse {
  string user_id = 1;
  bool success = 2;
  string error_message = 3;
}

message UserDetails {
  string id = 1;
  string username = 2;
  string email = 3;
  string created_at = 4;
}