export const MEASURMENT = {
  MEASUREMENT_UNIT: "Item",
  MEASUREMENT_TSP: "Tsp",
  MEASUREMENT_TBSP: "Tbsp",
  MEASUREMENT_CUP: "Cup(s)",
  MEASUREMENT_MILLILITER: " mL",
  MEASUREMENT_LITER: "L",
  MEASUREMENT_GRAM: "g",
};
